# Generated by Django 4.1.1 on 2022-10-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuccoresequence',
            name='accession_number',
            field=models.CharField(max_length=255),
        ),
    ]
