# Generated by Django 4.1.1 on 2022-10-10 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0003_alter_blastdb_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuccoresequence',
            name='uid',
            field=models.CharField(blank='', default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='nuccoresequence',
            name='owner_database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='barcode_blastn.blastdb'),
        ),
    ]
