# Generated by Django 4.1.1 on 2022-10-11 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0004_nuccoresequence_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastdb',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BlastRun',
            fields=[
                ('blastdb_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='barcode_blastn.blastdb')),
                ('runtime', models.DateTimeField(auto_now_add=True)),
                ('job_name', models.CharField(blank='', default='', max_length=255)),
                ('blastdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_used', to='barcode_blastn.blastdb')),
            ],
            bases=('barcode_blastn.blastdb',),
        ),
    ]
