# Generated by Django 4.1.2 on 2022-10-20 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0007_remove_blastrun_blastdb_blastrun_db_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuccoresequence',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_accession_version', models.CharField(max_length=128)),
                ('subject_accession_version', models.CharField(max_length=128)),
                ('percent_identity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('alignment_length', models.IntegerField()),
                ('mismatches', models.IntegerField()),
                ('gap_opens', models.IntegerField()),
                ('query_start', models.IntegerField()),
                ('query_end', models.IntegerField()),
                ('sequence_start', models.IntegerField()),
                ('sequence_end', models.IntegerField()),
                ('evalue', models.DecimalField(decimal_places=100, max_digits=110)),
                ('bit_score', models.DecimalField(decimal_places=100, max_digits=110)),
                ('owner_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='barcode_blastn.blastrun')),
            ],
        ),
    ]
