# Generated by Django 4.1.2 on 2022-10-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0009_remove_blastrun_blastdb_ptr_blastrun_id'),
    ]

    operations = [
    ]
