version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=barcode_identifier_db
      - POSTGRES_PASSWORD=psql27nv123mkhfpq2
    volumes:
      - pgdata:/var/lib/postgresql/data  
  pyvenv_image:
    container_name: pyvenv_image
    build: .
    depends_on:
      - db
  barcode_identifier_api:
    image: pyvenv_image
    build:
      context: ./compose/barcode_identifier_api
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=django-insecure-@-1(slvmd97@z722#ow(lffbv%%!#1#vy21&_5a&ku-c=xlh!9
      - DEBUG=1
      - DB_NAME=barcode_identifier_db
      - DB_USER=admin
      - DB_PASSWORD=psql27nv123mkhfpq2
      - DB_HOST=db
      - DB_PORT=5432
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ".:/barcode_identifier_api"
      # only for dev container: link the /data/runs and /var/www/runs folder to see files in local directories
      - "./var/data:/var/data/"
      - "./var/web:/vol/static"
    depends_on:
      - db
      - celery_worker
  rabbitmq:
    image: bitnami/rabbitmq:latest
    environment:
      - RABBITMQ_PASSWORD=bitnami
      - RABBITMQ_USERNAME=user
  celery_worker:
    image: pyvenv_image
    build: 
      context: ./compose/celery_worker
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=django-insecure-@-1(slvmd97@z722#ow(lffbv%%!#1#vy21&_5a&ku-c=xlh!9
      - DEBUG=1
      - DB_NAME=barcode_identifier_db
      - DB_USER=admin
      - DB_PASSWORD=psql27nv123mkhfpq2
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ".:/barcode_identifier_api"
      - "./var/data:/var/data/"
      - "./var/web:/vol/static/"
    command: >
      sh -c "celery_run.sh"
    depends_on:
      - rabbitmq
      - db
      
volumes:
  pgdata:

