version: '3'

services:
  barcode_identifier_api:
    build:
      context: .
    # auto-restart on crash
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    # for persistance, we used named volume that will be always stored on the server
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - barcode_identifier_api
    ports:
      - 80:8000
    # static-data is shared between app and proxy
    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  static-data:
