# Generated by Django 4.1.3 on 2023-02-07 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barcode_blastn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment_job_id', models.CharField(blank=True, default='', max_length=100)),
                ('tree_job_id', models.CharField(blank=True, default='', max_length=100)),
                ('internal_status', models.CharField(choices=[('STA', 'STARTING'), ('ALN', 'ALIGNING'), ('PRO', 'PROCESSING'), ('CON', 'CONSTRUCTING'), ('CLE', 'CLEANING'), ('FIN', 'FINISHED'), ('ERR', 'ERRORED')], default='STA', max_length=3)),
                ('owner_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree', to='barcode_blastn.blastrun')),
            ],
        ),
    ]
