# Generated by Django 4.1.3 on 2023-02-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttree',
            name='internal_status',
            field=models.CharField(choices=[('ALN', 'ALIGNING'), ('PRO', 'PROCESSING'), ('CON', 'CONSTRUCTING'), ('CLE', 'CLEANING'), ('FIN', 'FINISHED'), ('ERR', 'ERRORED')], default='ALN', max_length=3),
        ),
    ]
