# Generated by Django 4.1.3 on 2023-02-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_tree', '0002_alter_resulttree_internal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resulttree',
            name='tree_job_id',
        ),
    ]
