# Generated by Django 4.1.2 on 2022-11-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0002_rename_uuid_blastdb_id_rename_uuid_blastrun_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastrun',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
