# Generated by Django 4.1.1 on 2022-10-10 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlastDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('custom_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['custom_name'],
            },
        ),
        migrations.CreateModel(
            name='NuccoreSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accession_number', models.CharField(blank=True, default='', max_length=255)),
                ('definition', models.CharField(blank=True, default='', max_length=255)),
                ('organism', models.CharField(blank=True, default='', max_length=255)),
                ('organelle', models.CharField(blank=True, default='', max_length=255)),
                ('mol_type', models.CharField(blank=True, default='', max_length=255)),
                ('isolate', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('specimen_voucher', models.CharField(blank=True, default='', max_length=150)),
                ('dna_sequence', models.TextField(blank=True, default='', max_length=10000)),
                ('translation', models.TextField(blank=True, default='', max_length=10000)),
                ('owner_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcode_blastn.blastdb')),
            ],
            options={
                'ordering': ['accession_number'],
            },
        ),
    ]
