# Generated by Django 4.1.3 on 2024-11-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSequence',
            fields=[
            ],
            options={
                'ordering': ['accession_number'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('barcode_blastn.nuccoresequence',),
        ),
    ]
