# Generated by Django 4.1.3 on 2023-02-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0002_blastrun_alignment_job_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastrun',
            name='db_tree',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='blastrun',
            name='hit_tree',
            field=models.TextField(blank=True, default=''),
        ),
    ]
