# Generated by Django 4.1.1 on 2022-10-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0002_alter_nuccoresequence_accession_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blastdb',
            name='custom_name',
            field=models.CharField(max_length=255),
        ),
    ]
