# Generated by Django 4.1.3 on 2024-11-24 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0002_customsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuccoresequence',
            name='genbank_modification_date',
            field=models.DateField(blank=True, default=None, help_text='Modification date of the GenBank entry, shown in the locus field of the flat file.', null=True),
        ),
        migrations.AlterField(
            model_name='nuccoresequence',
            name='taxon_class',
            field=models.ForeignKey(blank=True, help_text='Class of the source organism', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_member', related_query_name='class_members', to='barcode_blastn.taxonomynode'),
        ),
        migrations.AlterField(
            model_name='nuccoresequence',
            name='taxon_family',
            field=models.ForeignKey(blank=True, help_text='Family of the source organism', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_member', related_query_name='family_members', to='barcode_blastn.taxonomynode'),
        ),
        migrations.AlterField(
            model_name='nuccoresequence',
            name='taxon_genus',
            field=models.ForeignKey(blank=True, help_text='Genus of the source organism', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genus_member', related_query_name='genus_members', to='barcode_blastn.taxonomynode'),
        ),
        migrations.AlterField(
            model_name='nuccoresequence',
            name='taxon_kingdom',
            field=models.ForeignKey(blank=True, help_text='Kingdom of the source organism', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kingdom_member', related_query_name='kingdom_members', to='barcode_blastn.taxonomynode'),
        ),
        migrations.AlterField(
            model_name='nuccoresequence',
            name='taxon_order',
            field=models.ForeignKey(blank=True, help_text='Order of the source organism', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_member', related_query_name='order_members', to='barcode_blastn.taxonomynode'),
        ),
        migrations.AlterField(
            model_name='nuccoresequence',
            name='taxon_phylum',
            field=models.ForeignKey(blank=True, help_text='Phylum of the source organism', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phylum_member', related_query_name='phylum_members', to='barcode_blastn.taxonomynode'),
        ),
        migrations.AlterField(
            model_name='nuccoresequence',
            name='taxon_species',
            field=models.ForeignKey(blank=True, help_text='Species taxa of the source organism', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_member', related_query_name='species_members', to='barcode_blastn.taxonomynode'),
        ),
        migrations.AlterField(
            model_name='nuccoresequence',
            name='taxon_superkingdom',
            field=models.ForeignKey(blank=True, help_text='Superkingdom of the source organism', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superkingdom_member', related_query_name='superkingdom_members', to='barcode_blastn.taxonomynode'),
        ),
    ]
