# Generated by Django 4.1.3 on 2023-02-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0003_blastrun_db_tree_blastrun_hit_tree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blastrun',
            name='query_sequence',
        ),
        migrations.AddField(
            model_name='blastrun',
            name='job_error_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
