# Generated by Django 4.1.2 on 2022-11-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0004_remove_blastrun_finished_blastrun_job_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='db_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barcode_blastn.nuccoresequence'),
        ),
    ]
