# Generated by Django 4.1.3 on 2023-04-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0005_remove_nuccoresequence_mol_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blastdb',
            options={'ordering': ['custom_name'], 'verbose_name': 'BLAST Database', 'verbose_name_plural': 'BLAST Databases'},
        ),
        migrations.AlterModelOptions(
            name='blastrun',
            options={'ordering': ['runtime'], 'verbose_name': 'BLASTN Run', 'verbose_name_plural': 'BLASTN Runs'},
        ),
    ]
