# Generated by Django 4.1.1 on 2022-10-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0005_blastdb_locked_blastrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastrun',
            name='blast_version',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blastrun',
            name='errors',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='blastrun',
            name='query_sequence',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blastrun',
            name='job_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
