# Generated by Django 4.1.2 on 2022-11-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0005_hit_db_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='db_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='barcode_blastn.nuccoresequence'),
            preserve_default=False,
        ),
    ]
