# Generated by Django 4.1.3 on 2023-05-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0006_alter_blastdb_options_alter_blastrun_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blastdb',
            options={'ordering': ['custom_name'], 'permissions': [('can_view_db', 'Can view BLAST Database'), ('can_edit_db', 'Can edit BLAST Database')], 'verbose_name': 'BLAST Database', 'verbose_name_plural': 'BLAST Databases'},
        ),
        migrations.AlterModelOptions(
            name='blastquerysequence',
            options={'verbose_name': 'BLASTN Query Sequence', 'verbose_name_plural': 'BLASTN Query Sequences'},
        ),
        migrations.AlterModelOptions(
            name='hit',
            options={'ordering': ['percent_identity'], 'verbose_name': 'BLASTN Run Hit', 'verbose_name_plural': 'BLASTN Run Hits'},
        ),
        migrations.AlterModelOptions(
            name='nuccoresequence',
            options={'ordering': ['accession_number'], 'verbose_name': 'GenBank Accession', 'verbose_name_plural': 'GenBank Accessions'},
        ),
        migrations.AddField(
            model_name='blastdb',
            name='public',
            field=models.BooleanField(default=False, help_text='Is this database accessible to the public?'),
        ),
    ]
