# Generated by Django 4.1.2 on 2022-11-21 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0007_blastdb_description_nuccoresequence_lat_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastQuerySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=255)),
                ('query_sequence', models.CharField(max_length=10000)),
                ('owner_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='barcode_blastn.blastrun')),
            ],
        ),
    ]
