# Generated by Django 4.1.3 on 2023-05-01 14:53

from django.db import migrations, models
import django.db.models.deletion

from barcode_blastn.models import BlastDb

def assign_owner_as_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Databases = apps.get_model('barcode_blastn', 'blastdb')
    Databases.objects.update(owner=User.objects.first())

def revert_owner(apps, schema_editor):
    Databases = apps.get_model('barcode_blastn', 'blastdb')
    Databases.objects.update(owner=None)

class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0007_alter_blastdb_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="blastdb",
            name="owner",
            field=models.ForeignKey(
                null=True, db_constraint=False, on_delete=django.db.models.deletion.PROTECT,
                                    to='auth.user', verbose_name='Owner'
            ),
        ),
        migrations.RunPython(assign_owner_as_admin, reverse_code=revert_owner),
        migrations.AlterField(
            model_name='blastdb',
            name='owner',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT,
                                    to='auth.user', verbose_name='Owner')
        ),
    ]
