# Generated by Django 4.1.2 on 2022-10-22 20:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0008_alter_nuccoresequence_uid_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blastrun',
            name='blastdb_ptr',
        ),
        migrations.AddField(
            model_name='blastrun',
            name='uuid',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4),
        ),

    ]
