# Generated by Django 4.1.3 on 2023-05-01 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barcode_blastn', '0008_add_owner_auth1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blastdb',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DatabaseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perms', models.CharField(choices=[('deny_access', 'Deny Access'), ('can_view_db', 'Can View Db'), ('can_edit_db', 'Can Edit Db')], default='deny_access', help_text='Access permissions', max_length=16)),
                ('database', models.ForeignKey(help_text='The database these permissions apply to.', on_delete=django.db.models.deletion.CASCADE, to='barcode_blastn.blastdb')),
                ('grantee', models.ForeignKey(help_text='User that the permissions apply to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blastdb',
            name='shares',
            field=models.ManyToManyField(related_name='projects_shared', through='barcode_blastn.DatabaseShare', to=settings.AUTH_USER_MODEL),
        ),
    ]
