# Generated by Django 4.1.3 on 2023-05-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0009_alter_blastdb_owner_databaseshare_blastdb_shares'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blastdb',
            options={'ordering': ['custom_name'], 'verbose_name': 'BLAST Database', 'verbose_name_plural': 'BLAST Databases'},
        ),
        migrations.AlterField(
            model_name='databaseshare',
            name='perms',
            field=models.CharField(choices=[('deny_access', 'Deny Access'), ('can_run_db', 'Can Run Db'), ('can_view_db', 'Can View Db'), ('can_edit_db', 'Can Edit Db')], default='deny_access', help_text='Access permissions', max_length=16),
        ),
    ]
