# Generated by Django 4.1.3 on 2023-05-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0010_alter_blastdb_options_alter_databaseshare_perms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaseshare',
            options={'verbose_name': 'BLAST Database Access Permission', 'verbose_name_plural': 'BLAST Database Access Permissions'},
        ),
    ]
