# Generated by Django 4.1.2 on 2022-10-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_blastn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blastdb',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='blastrun',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='nuccoresequence',
            old_name='uuid',
            new_name='id',
        ),
    ]
